---

- name: service - setup and run
  runit:
    name: strider
    enabled: yes
    state: start
    timeout: 10
    user: "{{ strider_user }}"
    command: "{{ strider_install_dir }}/start.sh"
  register: strider_service_status

